spring:
  #关闭spring session不然会报错
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.94.106:3307/spring-security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: rbjf_DEV123

server:
  port: 8088
#security:
#  basic:
#    enabled: false
#此配置项存在的时候,系统走/demo-login.html,没有的话走标准;我们需要把配置项进行封装到类里面去
yxm:
  security:
     social:
       filterProcessesUrl: /qqLogin
       qq:
         app-id: 101386962
         app-secret: 2a0f820407df400b84a854d054be8b6a
         providerId: callback.do
     browser:
#      loginPage: /demo-login.html
       loginType: JSON
#     code:
#       image:
#         length: 6
#         width: 100
#         url: /user,/user/*
