spring:
  #关闭spring session不然会报错
  session:
    store-type: none
server:
  port: 8088
#security:
#  basic:
#    enabled: false
#此配置项存在的时候,系统走/demo-login.html,没有的话走标准;我们需要把配置项进行封装到类里面去
yxm:
  security:
     browser:
#      loginPage: /demo-login.html
       loginType: JSON